# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VpLpncLcMvmavXkRBIOz6Gv7ukORKX0C
"""

a=7.5
s=(a**2*(3**(1/2)))/4
print(s)

a=int(input())
b=int(input())
c=int(input())
x=(a**2+b**2-c**3)/2
print(x)

a=5
b=int(input())
s=a*b
print(s)

a=int(input())
b=int(input())
s=(a+b)**2
print(s)

a=15
b=10
c=int(input())
s=(a+b)/c
print(s)

a=int(input())
b=int(input())
s=(a+b)**2
print("(",a, "+", b, ")","^","2","=", s)

a=int(input())
b=int(input())
c=int(input())
P=a+b+c
p=P/2
s=(p*(p-a)*(p-b)*(p-c))**(1/2)
print("S=",s,"P=",P)

a=int(input())
b=int(input())
s=((a**3+14)/5)*b
print(s)

a=int(input())
a1=a**2
n=int(input())
s=a1//n
print(s)

a=float(input())
b=float(input())
s=a//b
print(s)
a=int(input())
b=int(input())
s=a*b
print(s)
a=int(input())
b=int(input())
s=a%b
print(s)