# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ajx5USd6FNRVRdZ-BsT8cdUR7trPklT
"""

a=int(input())
if a==1:
    print("январь")
elif a==2:
    print("февраль")
elif a==3:
    print("март")
elif a==4:
    print("апрель")
elif a==5:
    print("май")
elif a==6:
    print("июнь")
elif a==7:
    print("июль")
elif a==8:
    print("август")
elif a==9:
    print("сентябрь")
elif a==10:
    print("октябрь")
elif a==11:
    print("ноябрь")
elif a==12:
    print("декабрь")

a=int(input())
if a%2==0:
  print("число четное")
else:
  print("число нечетное")

N=int(input())
if N>40:
  print("stonks")
elif N<40:
  print("not stonks")



def is_year_leap():
  year=int(input())
  if year % 4 != 0 or (year%100==0 and year%400==0):
    return False
  else:
    return True
is_year_leap()

def is_prime():
  n=int(input())
  a=False
  for  i in range(2,n):
    if n%i==0:
      a=False
      break
    else:
      a=True
      
  return(a)
is_prime()

a=int(input())
b=int(input())
if a/b>=3.6 or (b<=abs((-138/2)**1.3) and b>=abs((-69/28**5.1)*4)):
  a,b=b,a
print(a,b)

a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=int(input())
if (a==b) or (a==c) or (a==d) or (a==e) or (b==c) or (b==d) or (b==e) or (c==d) or (c==e) or (d==e):
  print("Не все числа уникальны")
else:
  print("Все числа уникальны")
cnt=0
if a%2==0:
  cnt=cnt+1
if b%2==0:
  cnt=cnt+1
if c%2==0:
  cnt=cnt+1
if d%2==0:
  cnt=cnt+1
if e%2==0:
  cnt=cnt+1
print("Количество четных чисел =",cnt)
cnt2=0
if a<0:
  cnt2=cnt2+1
if b<0:
  cnt2=cnt2+1
if c<0:
  cnt2=cnt2+1
if d<0:
  cnt2=cnt2+1
if e<0:
  cnt2=cnt2+1
print("Количество отрицательных чисел =", cnt2)
cnt3=0
if -256<=a<=1024:
  cnt3=cnt3+1
if -256<=b<=1024:
  cnt3=cnt3+1
if -256<=c<=1024:
  cnt3=cnt3+1
if -256<=d<=1024:
  cnt3=cnt+1
if -256<=e<=1024:
  cnt3=cnt3+1
print("Количество чисел на промежутке [-256;1024] =",cnt3)